<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Banco Azul - Iniciar sesión</title>
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/fa/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="css/signin.css">
</head>
<body>